name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Deno Install
        run: |
          deno install --frozen

      - name: Lint
        run: |
          deno lint
          deno --allow-read --allow-env --allow-sys eslint
        continue-on-error: true

      - name: Check Formatting
        run: |
          deno fmt --check
        continue-on-error: true

      - name: Type Check
        run: |
          deno check
        continue-on-error: true

      - name: Build
        run: |
          deno task build

      - name: Test
        run: |
          deno test --allow-net=:8000 --allow-run=deno
